from .FeedForwardNeuronalNetwork import FeedForwardNeuronalNetwork
from .CompressedNeuronalNetwork import CompressedNeuronalNetwork
from .MnistNetwork import MnistNetwork
from .ApproximationNeuralNetwork import ApproximationNeuralNetwork
