from .NeuronalNetwork import NeuronalNetwork
from .FeedForwardNeuronalNetwork import FeedForwardNeuronalNetwork
from .InvertableNeuronalNetwork import InvertableNeuronalNetwork
from .MnistNetwork import MnistNetwork
from .ApproximationNeuralNetwork import ApproximationNeuralNetwork
from .CompressableNeuronalNetwork import CompressableNeuronalNetwork
